{% set name = "repype" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/repype-{{ version }}.tar.gz
  sha256: 44e1b3930bd79a01dba7de7513ac8a7f353c84bb0e4853ba3a2623b50208ac03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dill >=0.3.2
    - frozendict >=2.4
    - mergedeep >=1.3.4
    - pyyaml >=6.0.1
    - watchdog >=4.0.2
    - textual ==0.76.0
    - pandas >=2,<3

test:
  imports:
    - repype
    - repype.textual
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kostrykin/repype
  summary: Reproducible batch processing using pipelines for scientific computing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kostrykin
