{% set name = "repype" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/repype-{{ version }}.tar.gz
  sha256: aa7503478e84e31693ad7a16500c0a624a488a22cbd246ad3ac610063258dbc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - dill >=0.3.2
    - frozendict >=2.4
    - mergedeep >=1.3.4
    - pyyaml >=6.0.1
    - watchdog >=4.0.2
    - textual ==0.76.0
    - pandas >=2,<3

test:
  imports:
    - repype
    - repype.textual
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kostrykin/repype
  summary: Reproducible batch processing using pipelines for scientific computing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kostrykin
